name: sns-testing-start
runs:
  using: "composite"
  steps:
    - name: Download sns_testing_bundle
      shell: bash
      run: |
        mkdir -p ic-bin
        cd ic-bin
        OS=linux
        IC_COMMIT=0e4c8234a9e0508ae30c5b8a7498406294c25e95
        CDN=https://download.dfinity.systems
        NAME=sns_testing_bundle
        curl --fail -L -O "$CDN/ic/${IC_COMMIT}/binaries/x86_64-${OS}/$NAME.tar.gz"
        tar -xvf ./$NAME.tar.gz

    - name: Start pocket-ic
      shell: bash
      run: |
        cd ic-bin
        nohup ./rs/pocket_ic_server/pocket-ic-server --ttl 3000 --port 8888 > pocket-ic.log 2>&1 &
        echo $! > pocket-ic.pid
        echo "POCKET_IC_PID=$(cat pocket-ic.pid)" >> $GITHUB_ENV
        echo "POCKET_IC_URL=http://127.0.0.1:8888" >> $GITHUB_ENV

    - name: Init sns-testing
      shell: bash
      run: |
        cd ic-bin
        source ./sns_testing_env.sh
        ./sns-testing-init --server-url "http://127.0.0.1:8888" --dev-identity sns-testing
