/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as NnsIndexRouteImport } from './routes/nns/index'
import { Route as homepageIndexRouteImport } from './routes/(homepage)/index'
import { Route as NnsProposalsIndexRouteImport } from './routes/nns/proposals/index'
import { Route as NnsNeuronsIndexRouteImport } from './routes/nns/neurons/index'
import { Route as NnsAccountsIndexRouteImport } from './routes/nns/accounts/index'
import { Route as NnsProposalsIdIndexRouteImport } from './routes/nns/proposals/$id/index'
import { Route as NnsNeuronsIdIndexRouteImport } from './routes/nns/neurons/$id/index'

const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const NnsIndexRoute = NnsIndexRouteImport.update({
  id: '/nns/',
  path: '/nns/',
  getParentRoute: () => rootRouteImport,
} as any)
const homepageIndexRoute = homepageIndexRouteImport.update({
  id: '/(homepage)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NnsProposalsIndexRoute = NnsProposalsIndexRouteImport.update({
  id: '/nns/proposals/',
  path: '/nns/proposals/',
  getParentRoute: () => rootRouteImport,
} as any)
const NnsNeuronsIndexRoute = NnsNeuronsIndexRouteImport.update({
  id: '/nns/neurons/',
  path: '/nns/neurons/',
  getParentRoute: () => rootRouteImport,
} as any)
const NnsAccountsIndexRoute = NnsAccountsIndexRouteImport.update({
  id: '/nns/accounts/',
  path: '/nns/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const NnsProposalsIdIndexRoute = NnsProposalsIdIndexRouteImport.update({
  id: '/nns/proposals/$id/',
  path: '/nns/proposals/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const NnsNeuronsIdIndexRoute = NnsNeuronsIdIndexRouteImport.update({
  id: '/nns/neurons/$id/',
  path: '/nns/neurons/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homepageIndexRoute
  '/nns': typeof NnsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/nns/accounts': typeof NnsAccountsIndexRoute
  '/nns/neurons': typeof NnsNeuronsIndexRoute
  '/nns/proposals': typeof NnsProposalsIndexRoute
  '/nns/neurons/$id': typeof NnsNeuronsIdIndexRoute
  '/nns/proposals/$id': typeof NnsProposalsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homepageIndexRoute
  '/nns': typeof NnsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/nns/accounts': typeof NnsAccountsIndexRoute
  '/nns/neurons': typeof NnsNeuronsIndexRoute
  '/nns/proposals': typeof NnsProposalsIndexRoute
  '/nns/neurons/$id': typeof NnsNeuronsIdIndexRoute
  '/nns/proposals/$id': typeof NnsProposalsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(homepage)/': typeof homepageIndexRoute
  '/nns/': typeof NnsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/nns/accounts/': typeof NnsAccountsIndexRoute
  '/nns/neurons/': typeof NnsNeuronsIndexRoute
  '/nns/proposals/': typeof NnsProposalsIndexRoute
  '/nns/neurons/$id/': typeof NnsNeuronsIdIndexRoute
  '/nns/proposals/$id/': typeof NnsProposalsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nns'
    | '/settings'
    | '/nns/accounts'
    | '/nns/neurons'
    | '/nns/proposals'
    | '/nns/neurons/$id'
    | '/nns/proposals/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/nns'
    | '/settings'
    | '/nns/accounts'
    | '/nns/neurons'
    | '/nns/proposals'
    | '/nns/neurons/$id'
    | '/nns/proposals/$id'
  id:
    | '__root__'
    | '/(homepage)/'
    | '/nns/'
    | '/settings/'
    | '/nns/accounts/'
    | '/nns/neurons/'
    | '/nns/proposals/'
    | '/nns/neurons/$id/'
    | '/nns/proposals/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homepageIndexRoute: typeof homepageIndexRoute
  NnsIndexRoute: typeof NnsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  NnsAccountsIndexRoute: typeof NnsAccountsIndexRoute
  NnsNeuronsIndexRoute: typeof NnsNeuronsIndexRoute
  NnsProposalsIndexRoute: typeof NnsProposalsIndexRoute
  NnsNeuronsIdIndexRoute: typeof NnsNeuronsIdIndexRoute
  NnsProposalsIdIndexRoute: typeof NnsProposalsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nns/': {
      id: '/nns/'
      path: '/nns'
      fullPath: '/nns'
      preLoaderRoute: typeof NnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(homepage)/': {
      id: '/(homepage)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homepageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nns/proposals/': {
      id: '/nns/proposals/'
      path: '/nns/proposals'
      fullPath: '/nns/proposals'
      preLoaderRoute: typeof NnsProposalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nns/neurons/': {
      id: '/nns/neurons/'
      path: '/nns/neurons'
      fullPath: '/nns/neurons'
      preLoaderRoute: typeof NnsNeuronsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nns/accounts/': {
      id: '/nns/accounts/'
      path: '/nns/accounts'
      fullPath: '/nns/accounts'
      preLoaderRoute: typeof NnsAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nns/proposals/$id/': {
      id: '/nns/proposals/$id/'
      path: '/nns/proposals/$id'
      fullPath: '/nns/proposals/$id'
      preLoaderRoute: typeof NnsProposalsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nns/neurons/$id/': {
      id: '/nns/neurons/$id/'
      path: '/nns/neurons/$id'
      fullPath: '/nns/neurons/$id'
      preLoaderRoute: typeof NnsNeuronsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homepageIndexRoute: homepageIndexRoute,
  NnsIndexRoute: NnsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  NnsAccountsIndexRoute: NnsAccountsIndexRoute,
  NnsNeuronsIndexRoute: NnsNeuronsIndexRoute,
  NnsProposalsIndexRoute: NnsProposalsIndexRoute,
  NnsNeuronsIdIndexRoute: NnsNeuronsIdIndexRoute,
  NnsProposalsIdIndexRoute: NnsProposalsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
