/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SnsIndexRouteImport } from './routes/sns/index'
import { Route as NnsIndexRouteImport } from './routes/nns/index'
import { Route as homepageIndexRouteImport } from './routes/(homepage)/index'
import { Route as VaultNameRouteImport } from './routes/vault/$name'
import { Route as NnsProposalProposalRouteImport } from './routes/nns/proposal/$proposal'

const SnsIndexRoute = SnsIndexRouteImport.update({
  id: '/sns/',
  path: '/sns/',
  getParentRoute: () => rootRouteImport,
} as any)
const NnsIndexRoute = NnsIndexRouteImport.update({
  id: '/nns/',
  path: '/nns/',
  getParentRoute: () => rootRouteImport,
} as any)
const homepageIndexRoute = homepageIndexRouteImport.update({
  id: '/(homepage)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultNameRoute = VaultNameRouteImport.update({
  id: '/vault/$name',
  path: '/vault/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const NnsProposalProposalRoute = NnsProposalProposalRouteImport.update({
  id: '/nns/proposal/$proposal',
  path: '/nns/proposal/$proposal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/vault/$name': typeof VaultNameRoute
  '/': typeof homepageIndexRoute
  '/nns': typeof NnsIndexRoute
  '/sns': typeof SnsIndexRoute
  '/nns/proposal/$proposal': typeof NnsProposalProposalRoute
}
export interface FileRoutesByTo {
  '/vault/$name': typeof VaultNameRoute
  '/': typeof homepageIndexRoute
  '/nns': typeof NnsIndexRoute
  '/sns': typeof SnsIndexRoute
  '/nns/proposal/$proposal': typeof NnsProposalProposalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/vault/$name': typeof VaultNameRoute
  '/(homepage)/': typeof homepageIndexRoute
  '/nns/': typeof NnsIndexRoute
  '/sns/': typeof SnsIndexRoute
  '/nns/proposal/$proposal': typeof NnsProposalProposalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/vault/$name' | '/' | '/nns' | '/sns' | '/nns/proposal/$proposal'
  fileRoutesByTo: FileRoutesByTo
  to: '/vault/$name' | '/' | '/nns' | '/sns' | '/nns/proposal/$proposal'
  id:
    | '__root__'
    | '/vault/$name'
    | '/(homepage)/'
    | '/nns/'
    | '/sns/'
    | '/nns/proposal/$proposal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  VaultNameRoute: typeof VaultNameRoute
  homepageIndexRoute: typeof homepageIndexRoute
  NnsIndexRoute: typeof NnsIndexRoute
  SnsIndexRoute: typeof SnsIndexRoute
  NnsProposalProposalRoute: typeof NnsProposalProposalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sns/': {
      id: '/sns/'
      path: '/sns'
      fullPath: '/sns'
      preLoaderRoute: typeof SnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nns/': {
      id: '/nns/'
      path: '/nns'
      fullPath: '/nns'
      preLoaderRoute: typeof NnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(homepage)/': {
      id: '/(homepage)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homepageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$name': {
      id: '/vault/$name'
      path: '/vault/$name'
      fullPath: '/vault/$name'
      preLoaderRoute: typeof VaultNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nns/proposal/$proposal': {
      id: '/nns/proposal/$proposal'
      path: '/nns/proposal/$proposal'
      fullPath: '/nns/proposal/$proposal'
      preLoaderRoute: typeof NnsProposalProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  VaultNameRoute: VaultNameRoute,
  homepageIndexRoute: homepageIndexRoute,
  NnsIndexRoute: NnsIndexRoute,
  SnsIndexRoute: SnsIndexRoute,
  NnsProposalProposalRoute: NnsProposalProposalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
