/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SnsIndexRouteImport } from './routes/sns/index'
import { Route as NnsIndexRouteImport } from './routes/nns/index'
import { Route as homepageIndexRouteImport } from './routes/(homepage)/index'
import { Route as VaultNameRouteImport } from './routes/vault/$name'
import { Route as NnsProposalsRouteImport } from './routes/nns/proposals'
import { Route as NnsProposalsIndexRouteImport } from './routes/nns/proposals/index'
import { Route as NnsProposalsIdIndexRouteImport } from './routes/nns/proposals/$id/index'

const SnsIndexRoute = SnsIndexRouteImport.update({
  id: '/sns/',
  path: '/sns/',
  getParentRoute: () => rootRouteImport,
} as any)
const NnsIndexRoute = NnsIndexRouteImport.update({
  id: '/nns/',
  path: '/nns/',
  getParentRoute: () => rootRouteImport,
} as any)
const homepageIndexRoute = homepageIndexRouteImport.update({
  id: '/(homepage)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultNameRoute = VaultNameRouteImport.update({
  id: '/vault/$name',
  path: '/vault/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const NnsProposalsRoute = NnsProposalsRouteImport.update({
  id: '/nns/proposals',
  path: '/nns/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const NnsProposalsIndexRoute = NnsProposalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NnsProposalsRoute,
} as any)
const NnsProposalsIdIndexRoute = NnsProposalsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => NnsProposalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/nns/proposals': typeof NnsProposalsRouteWithChildren
  '/vault/$name': typeof VaultNameRoute
  '/': typeof homepageIndexRoute
  '/nns': typeof NnsIndexRoute
  '/sns': typeof SnsIndexRoute
  '/nns/proposals/': typeof NnsProposalsIndexRoute
  '/nns/proposals/$id': typeof NnsProposalsIdIndexRoute
}
export interface FileRoutesByTo {
  '/vault/$name': typeof VaultNameRoute
  '/': typeof homepageIndexRoute
  '/nns': typeof NnsIndexRoute
  '/sns': typeof SnsIndexRoute
  '/nns/proposals': typeof NnsProposalsIndexRoute
  '/nns/proposals/$id': typeof NnsProposalsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/nns/proposals': typeof NnsProposalsRouteWithChildren
  '/vault/$name': typeof VaultNameRoute
  '/(homepage)/': typeof homepageIndexRoute
  '/nns/': typeof NnsIndexRoute
  '/sns/': typeof SnsIndexRoute
  '/nns/proposals/': typeof NnsProposalsIndexRoute
  '/nns/proposals/$id/': typeof NnsProposalsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/nns/proposals'
    | '/vault/$name'
    | '/'
    | '/nns'
    | '/sns'
    | '/nns/proposals/'
    | '/nns/proposals/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/vault/$name'
    | '/'
    | '/nns'
    | '/sns'
    | '/nns/proposals'
    | '/nns/proposals/$id'
  id:
    | '__root__'
    | '/nns/proposals'
    | '/vault/$name'
    | '/(homepage)/'
    | '/nns/'
    | '/sns/'
    | '/nns/proposals/'
    | '/nns/proposals/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NnsProposalsRoute: typeof NnsProposalsRouteWithChildren
  VaultNameRoute: typeof VaultNameRoute
  homepageIndexRoute: typeof homepageIndexRoute
  NnsIndexRoute: typeof NnsIndexRoute
  SnsIndexRoute: typeof SnsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sns/': {
      id: '/sns/'
      path: '/sns'
      fullPath: '/sns'
      preLoaderRoute: typeof SnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nns/': {
      id: '/nns/'
      path: '/nns'
      fullPath: '/nns'
      preLoaderRoute: typeof NnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(homepage)/': {
      id: '/(homepage)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homepageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$name': {
      id: '/vault/$name'
      path: '/vault/$name'
      fullPath: '/vault/$name'
      preLoaderRoute: typeof VaultNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nns/proposals': {
      id: '/nns/proposals'
      path: '/nns/proposals'
      fullPath: '/nns/proposals'
      preLoaderRoute: typeof NnsProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nns/proposals/': {
      id: '/nns/proposals/'
      path: '/'
      fullPath: '/nns/proposals/'
      preLoaderRoute: typeof NnsProposalsIndexRouteImport
      parentRoute: typeof NnsProposalsRoute
    }
    '/nns/proposals/$id/': {
      id: '/nns/proposals/$id/'
      path: '/$id'
      fullPath: '/nns/proposals/$id'
      preLoaderRoute: typeof NnsProposalsIdIndexRouteImport
      parentRoute: typeof NnsProposalsRoute
    }
  }
}

interface NnsProposalsRouteChildren {
  NnsProposalsIndexRoute: typeof NnsProposalsIndexRoute
  NnsProposalsIdIndexRoute: typeof NnsProposalsIdIndexRoute
}

const NnsProposalsRouteChildren: NnsProposalsRouteChildren = {
  NnsProposalsIndexRoute: NnsProposalsIndexRoute,
  NnsProposalsIdIndexRoute: NnsProposalsIdIndexRoute,
}

const NnsProposalsRouteWithChildren = NnsProposalsRoute._addFileChildren(
  NnsProposalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  NnsProposalsRoute: NnsProposalsRouteWithChildren,
  VaultNameRoute: VaultNameRoute,
  homepageIndexRoute: homepageIndexRoute,
  NnsIndexRoute: NnsIndexRoute,
  SnsIndexRoute: SnsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
