use std::cell::RefCell;

use ic_asset_certification::{Asset, AssetCertificationError, AssetConfig, AssetRouter};
use ic_cdk::{init, post_upgrade, query};
use ic_http_certification::{Hash, HttpRequest, HttpResponse};
use ic_static_assets::include_assets;

thread_local! {
    static ASSET_ROUTER: RefCell<AssetRouter<'static>> = RefCell::new(AssetRouter::default());
}

// Original copied from: https://github.com/ilbertt/ic-static-assets/blob/main/packages/ic-static-assets/src/certification.rs#L32
const CUSTOM_CSP: &str = "default-src 'self' *.devenv.dfinity.network; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' *.devenv.dfinity.network http://*.devenv.dfinity.network http://localhost:* https://icp0.io https://*.icp0.io https://*.icp0.app https://icp-api.io https://fastly.jsdelivr.net; img-src 'self' https://*.icp0.io data: blob:; style-src * 'unsafe-inline'; style-src-elem * 'unsafe-inline'; font-src *; object-src 'none'; media-src 'self' data:; base-uri 'self'; frame-ancestors 'none'; form-action 'self'; upgrade-insecure-requests";

fn certify_my_assets(
    assets: Vec<Asset<'static, '_>>,
    mut asset_configs: Vec<AssetConfig>,
) -> Result<Hash, AssetCertificationError> {
    for config in asset_configs.iter_mut() {
        match config {
            AssetConfig::File { headers, .. } | AssetConfig::Pattern { headers, .. } => {
                // Remove existing CSP header
                headers.retain(|(name, _)| name != "content-security-policy");
                // Custom CSP
                headers.push((
                    "content-security-policy".to_string(),
                    CUSTOM_CSP.to_string(),
                ));
            }
            _ => {}
        }
    }
    ASSET_ROUTER.with_borrow_mut(|router| {
        router.certify_assets(assets, asset_configs)?;
        Ok(router.root_hash())
    })
}

fn serve_my_assets(root_hash: Vec<u8>, req: &HttpRequest<'static>) -> HttpResponse<'static> {
    ASSET_ROUTER.with_borrow(|router| {
        router
            .serve_asset(&root_hash, req)
            .expect("Failed to serve asset")
    })
}

// This is the important line that embeds the frontend assets into the backend!
include_assets!(
    "$CARGO_MANIFEST_DIR/../governance-app-frontend/dist",
    certify_my_assets,
    serve_my_assets
);

#[init]
fn init() {
    certify_assets_hook(); // <- generated by the `include_assets` macro, no need to import it
}

#[post_upgrade]
fn post_upgrade() {
    certify_assets_hook();
}

#[query]
fn http_request(req: HttpRequest<'static>) -> HttpResponse<'static> {
    http_request_handler(&req) // <- generated by the `include_assets` macro, no need to import it
}
