export const CANISTER_ID_GOVERNANCE_APP_BACKEND = process.env.CANISTER_ID_GOVERNANCE_APP_BACKEND;
export const CANISTER_ID_INTERNET_IDENTITY = process.env.CANISTER_ID_INTERNET_IDENTITY;
export const CANISTER_ID_ICP_LEDGER = process.env.CANISTER_ID_ICP_LEDGER;
export const CANISTER_ID_SELF = process.env.CANISTER_ID;
