# Use the base image previously created and published.
FROM ghcr.io/dfinity/governance-app/builder-base:0.0.3

WORKDIR /app
COPY . .

# Copy env variables, set DFX_NETWORK and DFX_HOST for mainnet
RUN ./scripts/config.sh -n ic

# Run the build chain.
RUN npm ci
RUN dfx generate
RUN npm run build
RUN cargo build --target wasm32-unknown-unknown --release -p governance-app-backend --locked
