import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

import { KnownNeuronExternalData } from '@features/voting/types';

// ESM compatible __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const INPUT_PATH = path.resolve(__dirname, '../data/known-neurons.tsv');
const OUTPUT_DIR = path.resolve(__dirname, '../src/features/voting/data');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'knownNeuronsSorting.ts');

// Simple TSV line parser
const parseTSVLine = (line: string): string[] => line.split('\t').map((s) => s.trim());

try {
  const tsvContent = fs.readFileSync(INPUT_PATH, 'utf-8');
  const lines = tsvContent.split(/\r?\n/).filter((line) => line.trim() !== '');

  // specific columns:
  // topic_id, topic_name, neuron_id, known_neuron_name, follower_voting_power, follower_count.

  const RESULT_MAP: Record<string, KnownNeuronExternalData> = {};

  // Start from 1 to skip header
  for (let i = 1; i < lines.length; i++) {
    const cols = parseTSVLine(lines[i]);
    if (cols.length < 6) continue;

    const topic_id = Number(cols[0]);
    const topic_name = cols[1];
    const neuron_id = cols[2];
    const known_neuron_name = cols[3];
    // Remove single quotes from numbers (e.g. 192'294'914)
    const follower_voting_power = Number(cols[4].replace(/'/g, '').replace(/,/g, ''));
    const follower_count = Number(cols[5].replace(/'/g, '').replace(/,/g, ''));

    RESULT_MAP[neuron_id] = {
      index: i,
      topic_id,
      topic_name,
      id: neuron_id,
      name: known_neuron_name,
      voting_power: follower_voting_power,
      follower_count,
    };
  }

  // Generate TS Content
  const tsContent = `// This file is auto-generated by scripts/convert-known-neurons.ts
// Do not modify manually.

import { KnownNeuronExternalData } from "../types";

export const KNOWN_NEURONS_SORTING_MAP: Record<string, KnownNeuronExternalData> = ${JSON.stringify(RESULT_MAP, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, tsContent);
  console.log(
    `Successfully generated ${OUTPUT_FILE} with ${Object.keys(RESULT_MAP).length} entries.`,
  );
} catch (error) {
  console.error('Error processing TSV:', error);
  process.exit(1);
}
