name: Check

on:
  workflow_call:

jobs:
  codestyle:
    name: Codestyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Check formatting
        run: npm run format

      - name: Check linting
        run: npm run lint

  build_stats:
    name: Build Stats
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required to post comments
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Run Build and Capture Output
        id: build_step
        run: |
          # We use a heredoc to capture the multi-line output of vite build
          echo "VITE_OUTPUT<<EOF" >> $GITHUB_ENV
          npm run build >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post Build Stats Comment
        uses: mshick/add-pr-comment@v2
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        with:
          message: |
            ### 📊 Build Bundle Stats
            The latest build generated the following assets:

            ```text
            ${{ env.VITE_OUTPUT }}
            ```
            *Generated by GitHub Actions*

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate .env file
        run: ./scripts/config.sh -n local

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Run unit tests
        run: npm run test

  e2e_tests:
    name: E2E
    uses: ./.github/workflows/e2e.yml
