name: Check

on:
  workflow_call:

jobs:
  codestyle:
    name: Codestyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Check formatting
        run: npm run format

      - name: Check linting
        run: npm run lint

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Run unit tests
        run: npm run test

  e2e_tests:
    name: E2E
    uses: ./.github/workflows/e2e.yml
    with:
      update-snapshots: false
