name: Pipeline Dev

on:
  pull_request:
  merge_group:

jobs:
  check:
    name: Codestyle & tests
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  # TEST, TO REMOVE
  deploy:
    name: Deployment
    needs: [check]
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit