name: Pipeline Main

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Codestyle & Tests
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  deploy:
    name: Deployment
    needs: [check]
    uses: ./.github/workflows/build.yaml
    secrets: inherit
