name: Pipeline Main

on:
  push:
    branches:
      - main
  pull_request: # to remove

jobs:
  check:
    name: Codestyle & tests
    uses: ./.github/workflows/check.yaml

  deploy:
    name: Deployment
    needs: [check]
    uses: ./.github/workflows/deploy.yaml