name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      BASE_URL: http://lqy7q-dh777-77777-aaaaq-cai.localhost:8080
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      # Requires for governance-app build before deployment
      - name: Install Rust & Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - name: Install dependencies
        run: npm ci

      - name: Confirm successful installation
        run: |
          node -v
          npm -v
          dfx --version
          dfx identity list

      # sns-testing
      - name: Install dfx
        uses: dfinity/setup-dfx@main
      - name: Create sns-testing identity
        run: |
          dfx identity new sns-testing --storage-mode=plaintext || true
          dfx identity use sns-testing
          dfx identity get-principal
      - uses: ./.github/actions/sns-testing-start
      # To speed up the backend build.
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Deploy governance-app
        run: |
          dfx canister create governance-app-backend
          dfx deploy governance-app-backend

          # Verify deployment
          echo "Waiting for server..."
          max_attempts=30
          for i in $(seq 1 $max_attempts); do
            if curl -i $BASE_URL | grep "200 OK" > /dev/null; then
              echo "Server is up!"
              break
            fi
            echo "Server not ready yet... attempt $i/$max_attempts"
            sleep 2

            if [ "$i" -eq "$max_attempts" ]; then
              echo "Server did not become ready after $max_attempts attempts, exiting."
              exit 1
            fi
          done

      - name: Get Playwright version
        id: playwright_version
        run: |
          echo "version=$(npm ls @playwright/test --depth=0 --json | jq -r '.dependencies["governance-app-frontend"].dependencies["@playwright/test"].version')" >> $GITHUB_OUTPUT
      - name: Show Playwright version
        run: echo "Using Playwright version ${{ steps.playwright_version.outputs.version }}"
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.playwright_version.outputs.version }}-all
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium firefox webkit

      - name: Run Playwright tests
        run: |
          npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: src/governance-app-frontend/playwright-report/
          retention-days: 30

      - uses: ./.github/actions/sns-testing-stop
        if: always()
