name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Check Node and npm versions
        run: |
          node -v
          npm -v

      - name: Install Rust & Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install dependencies
        run: npm ci

      - name: Install dfx
        uses: dfinity/setup-dfx@main

      - name: Create sns-testing identity
        run: |
          dfx identity new sns-testing --storage-mode=plaintext || true
          dfx identity use sns-testing
          dfx identity get-principal

      # - name: Install Bazel
      #   uses: bazelbuild/setup-bazel@v7
      #   with:
      #     bazel-version: 7.1.2 # or whatever version you need

      - name: Confirm successful installation
        run: |
          dfx --version
          dfx identity list

      - name: Download sns_testing_bundle
        run: |
          set -x
          dfx identity list
          mkdir ic
          cd ic
          IC_COMMIT=0e4c8234a9e0508ae30c5b8a7498406294c25e95
          OS=linux
          CDN=https://download.dfinity.systems
          NAME=sns_testing_bundle
          curl --fail -L -O "$CDN/ic/${IC_COMMIT}/binaries/x86_64-${OS}/$NAME.tar.gz"
          tar -xvf ./$NAME.tar.gz
          ls
          ls ..

      - name: Start pocket-ic
        run: |
          cd ic
          dfx identity list
          ./rs/pocket_ic_server/pocket-ic-server --ttl 3000 --port 8888 &
          echo $! > pocket-ic.pid
          # npx wait-on http://localhost:8080/ --timeout 120000

      # - name: Clone ic repo
      #   run: |
      #     git clone https://github.com/dfinity/ic.git
      #     cd ic
      #     git checkout 0e4c8234a9e0508ae30c5b8a7498406294c25e95

      # - name: Run sns-testing-init
      #   run: |
      #     cd ic
      #     bazel run //rs/sns/testing:sns-testing-init -- \
      #       --server-url "http://127.0.0.1:8888" \
      #       --dev-identity sns-testing

      # - name: Show the dir
      #   run: |
      #     echo "current dir"
      #     pwd
      #     echo "ls"
      #     ls
      #     echo "ls rs/pocket_ic_server/"
      #     ls rs/pocket_ic_server/

      # - name: Search for all canister
      #   run: |
      #     find . -type f -name "*.wasm.gz" | sort
      # - name: ls
      #   run: |
      #     ls -lat
      #     cat sns_testing_env.sh

      # - name: patch sns_testing_env.sh
      #   run: |
      #     chmod +w sns_testing_env.sh
      #     echo 'export LIFELINE_CANISTER_WASM_PATH="rs/sns/testing/sns_testing_canister.wasm.gz"' >> sns_testing_env.sh
      #     # cat sns_testing_env.sh

      - name: Init sns-testing
        run: |
          dfx identity list
          source ./ic/sns_testing_env.sh
          cd ic
          ./sns-testing-init \
            --server-url "http://127.0.0.1:8888" \
            --dev-identity sns-testing
          cd ..
          echo "🍎 ls"
          ls
          echo "🍎 0"
          dfx canister create governance-app-backend
          echo "🍎 1"
          dfx generate governance-app-backend
          echo "🍎 2"
          dfx deploy
          echo "🍎 3"
          # npm run setup &
          echo "🍎 4"

      # - name: Start frontend
      #   run: |
      #     npm start &
      #     echo $! > frontend.pid
      #     # wait until it responds
      # npx wait-on http://localhost:3000 --timeout 120000

      # - name: Deploy frontend
      #   run: |
      #     set -x
      #     echo "🍎 0"
      #     dfx canister create governance-app-backend
      #     echo "🍎 1"
      #     dfx generate governance-app-backend
      #     echo "🍎 2"
      #     dfx deploy
      #     echo "🍎 3"
      # npm run setup &
      # echo "🍎 4"
      # echo $! > frontend.pid
      # wait until it responds
      # npx wait-on http://lqy7q-dh777-77777-aaaaq-cai.localhost:8080 --timeout 120000

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: |
          echo "Waiting for server..."
          for i in {1..30}; do
            if curl -s --head http://lqy7q-dh777-77777-aaaaq-cai.localhost:8080 | grep "200 OK" > /dev/null; then
              echo "Server is up!"
              break
            fi
            echo "Server not ready yet... sleeping 2s"
            sleep 2
          done

          npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Cleanup background procs
        if: always()
        run: |
          kill $(cat pocket-ic.pid) || true
          kill $(cat frontend.pid) || true
