name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Check Node and npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      # - name: Install dfxvm
      #   run: |
      #     DFX_VERSION=0.27.0 sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
      #     echo "$HOME/.local/bin" >> $GITHUB_PATH

      # - name: Install dfx 0.27.0
      #   run: |
      #     dfxvm install 0.27.0
      #     dfxvm default 0.27.0

      - name: Install dfx
        uses: dfinity/setup-dfx@main
      - name: Create sns-testing identity
        run: |
          dfx identity new sns-testing --storage-mode=plaintext || true
          dfx identity use sns-testing
          dfx identity get-principal

      - name: Confirm successful installation
        run: |
          dfx --version
          dfx identity list

      # - name: Log dfx
      #   run: |
      #     dfx --version

      # - name: Setup dfx identity
      #   run: |
      #     dfx identity new ci-identity --storage-mode=plaintext || true
      #     dfx identity use ci-identity
      #     dfx identity get-principal

      - name: Download sns_testing_bundle
        run: |
          # IC_COMMIT=c053a4439e87b44609df469ed8fc0713a3c619a0
          IC_COMMIT=91732387a03c7c82bdaea6f78d7f8321cc8cb559
          OS=linux
          CDN=https://download.dfinity.systems
          NAME=sns_testing_bundle
          curl --fail -L -O "$CDN/ic/${IC_COMMIT}/binaries/x86_64-${OS}/$NAME.tar.gz"
          tar -xvf $NAME.tar.gz

      - name: Show the dir
        run: |
          echo "current dir"
          pwd
          echo "ls"
          ls
          echo "ls rs/pocket_ic_server/"
          ls rs/pocket_ic_server/

      - name: Start pocket-ic
        run: |
          ./rs/pocket_ic_server/pocket-ic-server --ttl 3000 --port 8888 &
          echo $! > pocket-ic.pid
          # npx wait-on http://127.0.0.1:8888 --timeout 120000

      - name: Search for all canister
        run: |
          find . -type f -name "*.wasm.gz" | sort

      - name: ls
        run: |
          ls -lat
          cat sns_testing_env.sh

      - name: patch sns_testing_env.sh
        run: |
          chmod +w sns_testing_env.sh
          echo 'export LIFELINE_CANISTER_WASM_PATH="rs/sns/testing/sns_testing_canister.wasm.gz"' >> sns_testing_env.sh
          cat sns_testing_env.sh

      - name: Init sns-testing
        run: |
          echo "🍏"
          cat sns_testing_env.sh
          # fake the LIFELINE_CANISTER
          # echo 'export LIFELINE_CANISTER_WASM_PATH="rs/sns/testing/sns_testing_canister.wasm.gz"' >> sns_testing_env.sh
          # echo "🍎"
          cat sns_testing_env.sh
          source sns_testing_env.sh
          ./sns-testing-init \
            --server-url "http://127.0.0.1:8888" \
            --dev-identity sns-testing \
            --deciding-nns-neuron-id 1

      - name: Start frontend
        run: |
          dfx deploy --network http://127.0.0.1:8080

      - name: Start frontend
        run: |
          npm start &
          echo $! > frontend.pid
          # wait until it responds
          npx wait-on http://127.0.0.1:3000 --timeout 120000

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm run test-e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Cleanup background procs
        if: always()
        run: |
          kill $(cat pocket-ic.pid) || true
          kill $(cat frontend.pid) || true
