name: Update Snapshots
on:
  workflow_dispatch:
  # Trigger on pull requests
  # pull_request:
  #   branches: [main, master]

jobs:
  guard-main:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.ref_name == 'main' }}
        run: |
          echo "🚨 Not allowed to update snapshots directly on \"main\"" branch 🚨"
          exit 1

  call-e2e:
    uses: ./.github/workflows/e2e.yml
    with:
      update-snapshots: true
