name: Update Snapshots
on:
  workflow_dispatch:
  # Trigger on pull requests
  # pull_request:
  #   branches: [main, master]

jobs:
  call-e2e:
    uses: ./.github/workflows/playwright.yml
    with:
      update-snapshots: true
